# Generated by Django 5.2.6 on 2025-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('DRUG', 'Drug'), ('SERVICE', 'Service')], max_length=12)),
                ('ref_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'invoice_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoicePrintLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('printed_at', models.DateTimeField()),
                ('copy_tag', models.CharField(max_length=8)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoice_print_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('VOID', 'Void')], max_length=8)),
                ('created_at', models.DateTimeField()),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(default='CASH', max_length=4)),
                ('paid_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
    ]
