LOG_ACTION = {
    "PENDING": "PENDING",
    "CONFIRMED": "CONFIRMED",
    "STARTED": "STARTED",
    "IN_PROGRESS": "IN_PROGRESS",
    "COMPLETED": "COMPLETED",
    "CANCELLED": "CANCELLED",
    "NO_SHOW": "NO_SHOW",
    "UPDATED_RECORD": "UPDATED_RECORD",
    "UPDATED_PRESCRIPTION": "UPDATED_PRESCRIPTION",
    "PRESCRIPTION_DRAFTED": "PRESCRIPTION_DRAFTED",
    "PRESCRIPTION_SIGNED": "PRESCRIPTION_SIGNED",
    "RESCHEDULED": "RESCHEDULED",
}


