# Generated by Django 5.2.6 on 2025-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFaqs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('locale', models.CharField(default='vi', max_length=10)),
                ('enabled', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'chatbot_faqs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('USER', 'User'), ('BOT', 'Bot')], max_length=4)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chatbot_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatbotSessions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=64, unique=True)),
                ('channel', models.CharField(default='WEB', max_length=3)),
                ('locale', models.CharField(default='vi', max_length=10)),
                ('state', models.CharField(default='ACTIVE', max_length=6)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chatbot_sessions',
                'managed': False,
            },
        ),
    ]
