# Generated by Django 5.2.6 on 2025-09-17 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientprofile'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('degree_title', models.CharField(blank=True, max_length=50, null=True)),
                ('default_work_days', models.CharField(blank=True, max_length=64, null=True)),
                ('default_start_time', models.TimeField(blank=True, null=True)),
                ('default_end_time', models.TimeField(blank=True, null=True)),
                ('default_slot_minutes', models.IntegerField(blank=True, null=True)),
                ('notify_web', models.BooleanField(default=True)),
                ('notify_today_shift', models.BooleanField(default=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='doctors.doctors')),
            ],
            options={
                'db_table': 'doctor_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserExtras',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('address_short', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='accounts.users')),
            ],
            options={
                'db_table': 'user_extras',
                'managed': True,
            },
        ),
    ]
