# Generated by Django 5.2.6 on 2025-09-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_create_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
